// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nexusid-landing/AppleGlass.tsx": () => import("../components/mockups/nexusid-landing/AppleGlass.tsx"),
  "./components/mockups/nexusid-landing/CyberOperator.tsx": () => import("../components/mockups/nexusid-landing/CyberOperator.tsx"),
  "./components/mockups/nexusid-landing/LinearRefined.tsx": () => import("../components/mockups/nexusid-landing/LinearRefined.tsx")
};
